---
title: "Final Project"
author: "Siyan Pu"
date: "12/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# import packages
library(dplyr)
library(ggplot2)
```

```{r}
data <- read.csv("ESS.csv")
# Specific Info: 
# European Social Survey is conducted every two years to collect data from individuals in different European countries on plenty of different fields such as politics, climate, and other social issues. This dataset can be accessed from https://www.kaggle.com/pascalbliem/european-social-survey-ess-8-ed21-201617/version/2#ESS8e02.1_F1.csv

# Data Introduction: There are 534 variables in total for each individual sampled from those European countries. I'll focus on several variables among them to solve my research questions. 
# happy: How happy are you?
# sclmeet: How often socially meet with friends, relatives or colleagues?
# inprdsc: How many people with whom you can discuss intimate and personal matters?
# sclact: Take part in social activities compared to others of same age
# marsts: Legal Marital Status
# cntry: country
# A detailed codebook is in the pdf Code Book with highlights
```

#Research Questions
```{r}
# 1. Do people in Europe who meets people more, have more people to talk, or take part in more social activities think they are happier? If not, does people in a legal relationship think they are happier?
# explanatory variable: sclmeet/inprdsc/sclact/marsts
# response variable: happy
# Expectation and Rationals: People in Europe who meet people more, have more people to talk, or take part in more social activities countries think they are happier/People in a legal relationship think they are happier. If people have someone to express their sadness and resort to when having difficulties, they'll be less likely to get depressed and are more likely to feel happy overall. Also, if people are in a legal relationship with someone, they are more likely to have more support in their lives than those who aren't and more likely to feel happy.


# 2. In Europe, does people in developed countreis think they are happeir than those in developing countries do? 
# explanatory variable: cntry
# response variable: happy
# Expectation and rationals: People in developed countries think they are happier. People are more likely to be happy when they have enough money to live a good life.
```

#Data Manipulation & Visualization
```{r}
# Research Question 1
# Step 1: Use dplyr to select the variables I need and then filter the invalid answers out according to the Codebook
data1 <- data %>%
  select(happy, sclmeet, inprdsc, sclact) %>%
  filter(happy != 77, happy != 88, happy != 99, sclmeet != 77, sclmeet != 88, sclmeet != 99, inprdsc != 77, inprdsc != 88, inprdsc != 99, sclact != 7, sclact != 8, sclact != 9)

# Step 2: Use ggplot to plot the explanatory and response variable correspondingly to check the patterns
ggplot(data1, aes(sclmeet, happy)) +
  geom_point()
ggplot(data1, aes(inprdsc, happy)) +
  geom_point()
ggplot(data1, aes(sclact, happy)) +
  geom_point()

## After ploting these three variables related to social activities with respect to variable happy, I found no obvious relationship between them. So I chose another variable marsts which represents marital status and plot it with respect to happy.

# Do data manipulation to the dataset to get variable I need this time; 
data3 <- data %>%
  select(happy, marsts) %>%
  filter(happy != 77, happy != 88, happy != 99, marsts != 77, marsts != 88, marsts != 99, marsts != 66) 

#Recode the variable marsts to if_mr dividing valid answers into two groups: in a legal relationship & not
if_mr <- factor(ifelse(data3$marsts == 1 | data3$marsts == 2, "In Legal Rlsp", "Not in Legal Rlsp"))

summary(if_mr)

# Add the recoded variable to the selected data and plot it with the repsonse variable "happy"
data3 %>%
  mutate(if_mr) %>%
  ggplot(aes(if_mr, happy)) + geom_boxplot(aes(color=if_mr))

# Research Question 2
# Recode the variable "cntry" to "cntry_ifdvlpd" which divides all the european countries into two groups: developed & developing
cntry_ifdvlpd <- factor(ifelse(data$cntry == "CZ" | data$cntry == "EE" | data$cntry == "HU" | data$cntry == "IS" | data$cntry == "LT" | data$cntry == "PL" | data$cntry == "SI" , "Developing Country", "Developed Country"))
summary(cntry_ifdvlpd)

# With dplyr, add the recoded variable to the dataset and select it and response variable "happy", and then filter the invalid answers out.
data2 <- data %>% 
  mutate(cntry_ifdvlpd) %>%
  select(happy, cntry_ifdvlpd) %>%
  filter(happy != 77, happy != 88, happy != 99) 

summary(data2$cntry_ifdvlpd)

# With ggplot, plot the explanatory variable "cntry_ifdvlpd" and response variable "happy" and observe the pattern
ggplot(data2, aes(cntry_ifdvlpd, happy)) +
  geom_boxplot(aes(color=cntry_ifdvlpd))

```

#Conclusions
```{r}
# Answers for research questions
# for question1, there isn't an obvious relationship between meeting people more, having more people to talk about personal matters, or taking part in more social activities and being happier. But people who are in a legal relationship do have a higher possibility to say they are happy.
# for question2, there is a higher percent of people in developed countries think they are happy than that in developing countries.

# In this dataset, there are many things that may be positively related to variable "happy." Therefore, it's difficult to directly observe the explanatory variables for it. I chose three at first, but failed to see the pattern. So my extra question is, what are the factors as variables in this dataset have positive relationships with response variable "happy"

```



